//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBrowser.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleBrowser.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a @using SimpleBrowser;
        ///@using System.Web;
        ///@{
        ///	bool lastItemIsLogMessage = false;
        ///}
        ///&lt;!doctype html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;@Model.Title&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body { font-family: Verdana, Sans-Serif; font-size: 11px; margin: 30px; color: #333; }
        ///			h1, h2, h3, p { margin: 0 0 15px 0; }
        ///			h1, h2, h3, h4 { font-family: Arial; color: black; }
        ///			h1 { font-size: 32px; color: #468966; letter-spacing: -1px; }
        ///			h2 { font-size: 24px; color: #8E2800; letter-spacing: -1px; }
        ///			h3 { fon [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string HtmlLogTemplate {
            get {
                return ResourceManager.GetString("HtmlLogTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a @using SimpleBrowser;
        ///@using System.Web;
        ///@{
        ///	bool lastItemIsLogMessage = false;
        ///}
        ///&lt;!doctype html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;@Model.Title&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body { font-family: Verdana, Sans-Serif; font-size: 11px; margin: 30px; color: #333; }
        ///			h1, h2, h3, p { margin: 0 0 15px 0; }
        ///			h1, h2, h3, h4 { font-family: Arial; color: black; }
        ///			h1 { font-size: 32px; color: #468966; letter-spacing: -1px; }
        ///			h2 { font-size: 24px; color: #8E2800; letter-spacing: -1px; }
        ///			h3 { fon [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string HtmlLogTemplateNetStandard {
            get {
                return ResourceManager.GetString("HtmlLogTemplateNetStandard", resourceCulture);
            }
        }
    }
}
